/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-01-31 05:25:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/config/tlds/spring.tld", Long.valueOf(1611904138647L));
    _jspx_dependants.put("/WEB-INF/config/tlds/c.tld", Long.valueOf(1611904138620L));
    _jspx_dependants.put("/WEB-INF/config/tlds/egov-ui.tld", Long.valueOf(1611904138627L));
    _jspx_dependants.put("/WEB-INF/config/tlds/spring-form.tld", Long.valueOf(1611904138639L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction idCked(){\r\n");
      out.write("\t\tvar user_id =  document.getElementById('memId').value;\r\n");
      out.write("\t\tvar jsonStr = JSON.stringify({user_id : user_id});\r\n");
      out.write("\t\tconsole.log(\"jsonStr : \" + jsonStr);\r\n");
      out.write("\t\t$.ajax({   \r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/userIdcked.do\" \r\n");
      out.write("\t        , method : \"get\" \r\n");
      out.write("\t\t\t, dataType : 'json'\r\n");
      out.write("\t\t\t, data : user_id   \r\n");
      out.write("\t\t\t, processData : true /*querySTring make false*/  \r\n");
      out.write("\t\t\t, contentType : \"application/json; charset=UTF-8\"\r\n");
      out.write("\t\t\t, success : function(data, stat, xhr) {\r\n");
      out.write("\t\t\t\talert(\"success\");\r\n");
      out.write("\t\t\t}   \r\n");
      out.write("\t\t    , error : function(xhr, stat, err) {\r\n");
      out.write("\t\t    \talert(\"error\");\r\n");
      out.write("\t\t    \tconsole.log(err);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"margin-top: 50px\">  \r\n");
      out.write("\t<form class=\"form-horizontal\" id=\"sendForm\">\r\n");
      out.write("\t    <div class=\"form-group\">\r\n");
      out.write("\t      <label class=\"col-sm-2 control-label\">ID</label>\r\n");
      out.write("\t      <div class=\"col-sm-4\">\r\n");
      out.write("\t        <input class=\"form-control\" id=\"memId\" name=\"memId\" type=\"text\" value=\"\" title=\"ID\">   \r\n");
      out.write("\t      </div>\r\n");
      out.write("\r\n");
      out.write("\t      <div class=\"container\">\r\n");
      out.write("\t      \t<button type=\"button\" id=\"idcked\" class=\"btn btn-default\" style=\"display: block;\" onclick=\"idCked()\" >ID 중복 체크</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\r\n");
      out.write("\t    </div> \r\n");
      out.write("\r\n");
      out.write("\t    <div class=\"form-group\">\r\n");
      out.write("\t      <label for=\"disabledInput \" class=\"col-sm-2 control-label\">패스워드</label>\r\n");
      out.write("\t      <div class=\"col-sm-4\">\r\n");
      out.write("\t        <input class=\"form-control\" id=\"pwd\" name=\"\" type=\"password\" title=\"패스워드\" >\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <label for=\"disabledInput \" class=\"col-sm-2 control-label\">패스워드 확인</label>\r\n");
      out.write("\t      <div class=\"col-sm-4\">\r\n");
      out.write("\t        <input class=\"form-control\" id=\"pwdck\" name=\"\" type=\"password\" title=\"패스워드 확인\">\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t    <div class=\"form-group\">\r\n");
      out.write("\t      <label for=\"disabledInput\" class=\"col-sm-2 control-label\">이름</label>\r\n");
      out.write("\t      <div class=\"col-sm-4\">\r\n");
      out.write("\t        <input class=\"form-control\" id=\"memName\" name=\"memName\" type=\"text\" value=\"\" title=\"이름\" >\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t    <div class=\"col-md-offset-4\">\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"saveBtn\"class=\"btn btn-primary\">저장</button>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"#\"class=\"btn btn-danger\">취소</button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
